### ISSUE TITLE
Consider falling-back to box86 55be683 with dotnet46 (instead of wine-mono)

### ISSUE THREAD

**Issue by WheezyE** [WheezyE/Winelink#14]
Notes to self: May need wine-devel-5.21 and `BOX86_DYNAREC=0 BOX86_NOBANNER=1 winetricks msxml3`. Experiment with dynarec envvar.

ptitSeb/box86-compatibility-list#46

Installation will likely take hours, with multiple shutdowns of the Pi for overheating.

**Comment by WheezyE** [comment]
https://github.com/ptitSeb/box86-compatibility-list/issues/46

**Comment by WheezyE** [comment]
dotnet40, dotnet45, dotnet46 can all be installed (individually) with box86, but all freeze at the end of their installers. After installation, dotnet46 does not appear to be detected by wine (says it needs to be 'enabled').  wine dll overrides are not set. Manually setting mscoree override to 'native' does not change program behavior.
 - Done: Log1 the individual installers.
 - TODO: Log0 the dotnet40 installer.

Running `BOX86_NOBANNER=1 winetricks -q dotnet46` does not work due to freezes.
 - TODO: Log0 the frozen spot & compare to Log1/0's of individual installers.

`BOX86_NOBANNER=1 winetricks -q dotnet48` installs fine, but is not usable by RMS Express.

**Comment by WheezyE** [comment]
Seb fixed dotnet46 in box86.  I haven't found a way to install dotnet46 with automation yet though (could be possible with another version of Wine or with AHK).

Install time is about 60+ minutes. Wine-mono would be a much better option than dotnet46.

**Comment by WheezyE** [comment]
To test:
 - See if any specific versions of wine cause hangups in `winetricks -q dotnet46` install chain
 - Keep up with box86 testing.
 - Report install chain hangups to Seb

**Comment by WheezyE** [comment]
Found a path forward for quiet installation of dotnet46 w/ box86 - re-implementing .NET until wine-mono bugs can be found/fixed.

**Comment by clort81** [comment]
------------------------------------------------------
warning: This package (dotnet46) is broken in wine-5.13. Broken since 5.12. Upgrade to >=5.18. See https://bugs.winehq.org/show_bug.cgi?id=49532 for more info. Use --force to try anyway.
------------------------------------------------------
same with 45, 48... how can we use twister os wine 5.13 with dotnet and box86?
