### ISSUE TITLE
Keep VARA only option

### ISSUE THREAD

**Issue by 5rm** [WheezyE/Winelink#15]
As the .NET seems to cause problems, could you please concider  keeping the version without it available. For many people your great script without WinlinkExpress is enough to run Vara on pi. Very soon there is Vara support in PAT which is a multiplatform replacement for WinlinkExpress.

73 Jouko oh5rm

**Comment by WheezyE** [comment]
Thank you for the kind words.  I had seen the Pat forum announcement about the VARA support coming in the next update too.  I let KM4ACK know yesterday about that just in case he wants to consider adding VARA HF/FM/Chat to BAP.

The current version of the Winelink script doesn't include .NET at the moment.  I've replaced .NET with wine-mono instead.  Wine-mono has its own set of bugs, but installs much quicker.

The difference in install time between [wine-mono + RMS + VARA HF/FM/Chat] vs [just VARA HF/FM/Chat] in the current script is maybe 5 minutes or so.  I could implement the `vara_only` argument again, but I think it's a small different in installation time.  I'm hoping to keep the complexity of the script low too in preparation of trying to implement more platforms (chrome, mac, other linux distros).

**Comment by WheezyE** [comment]
Wine-mono ended up having some extra bugs we need to fix, & Seb fixed some .NET 4.6 stuff, so I'm moving back to .NET for now.  I'll re-implement the vara_only option soon too!

**Comment by 5rm** [comment]
Yes, good to hear that you are going to keep the VARA_only option for those who do not need WLE and to whom robustness is the first priority.

**Comment by 5rm** [comment]
Eric,
I tried it again on a new SD with Bullseye, after two hours of looping had to break out with ctl-c.
It looks like it tries some .NET runtime optimization without end.
As many fellow hams would like to have VARA running on PI4, could you plese make a working script without the .net stuff which is causing problems.
I still have your earlier Vara only version running fine with vARIM and pilinbpq. That is what many people are asking, they do not need WinlinkExpress.

**Comment by 5rm** [comment]
Btw, I found that the basic wine and box86 were still ok. I manually installed and configured the rest and managed to get vara and vArim to run. Had to add some dll’s to system32 and add vb6runtime etc.

**Comment by WheezyE** [comment]
The ever since Winlink moved to using .NET 4.6 (instead of 3.5sp1), the .NET installation has become a lot longer in the script.  Apologies for the slow updates - the past month ended up being incredibly busy.  I've just now re-implemented the vara_only option with 54b8957e3b3d09e3ee40ab9e2e328e8b1cf0de06. I was able to test both regular and vara_only installations and both are still working on my end.  Hope this helps the installation process in the future!

**Comment by 5rm** [comment]
Screenshot from 2022-01-11 09-59-30

**Comment by 5rm** [comment]
![unnamed](https://user-images.githubusercontent.com/6057178/148905876-8e35dd38-a77d-4945-8796-498f9968e9c5.png)

**Comment by 5rm** [comment]
Just for information:
I yesterday installed also VARACHAT which uses COM instead of Linux /dev/ttyUSB0.
I had to use wine regedit to add an entry to the PORT  COM1... /dev/ttyUSB0 to get the PTT work.

**Comment by 5rm** [comment]
Terveisin
Jouko Nurma

**Comment by 5rm** [comment]
Terveisin
Jouko Nurma

**Comment by WheezyE** [comment]
> Just for information: I yesterday installed also VARACHAT which uses COM instead of Linux /dev/ttyUSB0. I had to use wine regedit to add an entry to the PORT COM1... /dev/ttyUSB0 to get the PTT work.

The re-implemented `vara_only` option will install VARA Chat too.

I haven't tried checking on COM port connections from the Pi yet, but I'll look at that later.  Were you having any PTT issues with the Pi with Vara Chat and the latest script?

I did do some work with a Debian Linux VM and the COM port issue with wine-mono and learned the following things about checking COM port permissions:
 - You can check to see which USB devices Wine has detected with `ls ~/.wine/dosdevices`
 - If you then run `ls -l ~/.wine/dosdevices/com5` (or any other com#), you should get some kind of output showing which hardware device is symlinked to that 'com#' (in my case on Debian x86 VM + FT-891: `lrwxrwxrwx 1 pi pi 12 Jan  3 19:26 /home/pi/.wine/dosdevices/com5 -> /dev/ttyUSB0`)
 - You can then check permissions to see if your user account has access to your USB ports with `ls -l /dev/ttyUSB0` (In my case on Debian x86 VM, this outputs: `crw-rw---- 1 root dialout 188, 1 Jan  3 19:50 /dev/ttyUSB0`, which I think tells me that the user account didn't have permission to use the COM ports, just the root and dialout accounts)
 - You can add the current user account to the COM port 'dialout' group with `sudo usermod -a -G dialout $USER && sudo reboot`

**Comment by 5rm** [comment]
Hi
My comment was referring to the situation before your re-implementing vara only when I manually installed all applications. I tried the methode in k6eta blog to direct com1 to /dev/ttyUSB0, but it didnt work for me. So I made it by editing the registry, which did work OK.
I have been busy but maybe tomorrow I can test the new vara only script. As I have no monitor/keybrd hooked to Pi I can use two ways ro run the script, either via VNC to desktop terminal, or via ssh. Regarding the script do you see any difference between those two? I think there was some popup windows to enter some settings  if I remember correctly.

- Jouko

**Comment by WheezyE** [comment]
Yes the script does not work with SSH - the script requires a “video” (X11) session to be active to be able to install, so VNC is the only headless install option.

Thinking over this more, the `vara_only` install should work basically the same as your manual install. I wonder if the COM port issue was a permissions issue (user account not included in the dialout permissions group)
