### ISSUE TITLE
Install Script will not complete.

### ISSUE THREAD

**Issue by wb8skp** [WheezyE/Winelink#30]
Using a PI4B, RigBlaster Advantage and IC756Pro. Installed ok and worked great. Later I installed DXKeeper and it worked ok. But Winelink loaded very slow and the stopped working. I started over by installing new OS. Then tried to install Winelink. The script always stops at trying to install "wine-mono"
73, Denis

**Comment by WheezyE** [comment]
Hey Dennis,
Thanks for trying out the Winelink alpha.

It looks like DxKeeper is a Windows program. I haven’t tested that with
Wine or box86, but I’m wondering if that might have caused the problem.
What does your wine-mono error message say exactly? (Can you copy/paste the
error message or screenshot it?) Which OS are you using?
73, Eric

**Comment by WheezyE** [comment]
You might also want to check your internet connection is working before doing the install. This is the wine-mono link that the current install uses. You don’t have to download this whole file to test your connection, but you might click on this to see if the file starts downloading: https://nightly.link/madewokherd/mono/actions/artifacts/154265073.zip

**Comment by wb8skp** [comment]
Eric,
First thanks for getting back to me so fast. I think you hit on my problem.
I started fresh this morning. This time I did not use the WIFI. Everything
installed and the program works great.
Yes DX Commander is a Windows program and it works ok on the PI using WINE.
I am not going to load it on this PI. I do not want to mess things up :-)
Keep up the good work.
Take care
Denis, WB8SKP

**Comment by WheezyE** [comment]
Awesome 😄 I'm glad it's working. I bet it was a poor wifi connection.

I installed DXKeeper just to see if it would interfere with VARA and it seems to coexist ok with it. I'd say feel free to reinstall that.
![image](https://user-images.githubusercontent.com/29649598/158039992-1a813f6a-5e85-4ad8-88d4-532449d4c81a.png)

```
cd ~/Downloads && wget http://www.dxlabsuite.com/dxkeeper/DXKeeper719Archive.exe # Download
wine DXKeeper719Archive.exe # Unpack (why is it in Italian? lol)
wine setup.exe # Install
wine ~/.wine/drive_c/Program\ Files/DXKeeper/DXKeeper.exe # Run
```

I'll close this issue, but let me know if you get any more trouble and I'll re-open it and do some more testing.

Thank you! And thank you for testing things out.
73 de KI7POL,
Eric

**Comment by wb8skp** [comment]
Thank you for trying DXKeeper. I will give it a try but for now I am going
to leave things like they are.
73, Denis
WB8SKP
