### ISSUE TITLE
RMS Express Crashes with VARA displaying Waterfall

### ISSUE THREAD

**Issue by sanityassass1n** [WheezyE/Winelink#32]
This project is progressing amazingly and working quite well (thanks WheezyE). One issue that I have noticed is that VARA itself works fine with the VARA waterfall displayed. However, RMS Express crashes with the VARA waterfall display selected but remains fairly stable if it is only showing the VARA gauges. This is on a 4B 4GB model and I've tried allocating various amounts of memory to the GPU and it has no effect.

**Comment by WheezyE** [comment]
Thanks for testing things out and for the kind words.  Now that you mention it, I think I've crashed VARA like that in the past too.  I'll have to maybe see if I can track down crashes that happen when VARA's waterfall is turned on and send them to Seb or WineHQ.  I've got a few feature requests & bugs on my 'workbench' at the moment, but this is a good reminder to try to track this one down for better stability.

If you wanted to poke around a bit with trying to find/log/submit this one, you might try testing to see if it happens in wine on PC Linux or if it only happens in wine on RPi/box86.  If it's only happening in box86, you might then try running `BOX86_LOG=1 BOX86_DYNAREC_BIGBLOCK=0 wine ~/.wine/drive_c/RMS\ Express/RMS\ Express.exe 2>&1 | tee log1.txt` to see if you can capture the exact moment that the crash happens in a box86 log, then submit that text file (NOT COPY-PASTE) to the box86 github.

**Comment by WheezyE** [comment]
I am still getting the RMS Express + VARA HF (with waterfall) crash on my on my Pi4B 4GB 7mo later despite box86 and wine development.

I'm deciding to give up on this bug for now since it's not critical, just annoying.  I'm going to add it to known bugs with a workaround. Thank you for reporting it in. I'll keep it on my radar and re-open this if I find more info later.
