### ISSUE TITLE
RMS express linking with VARA on Pi 4B 32 bit Bullseye build with Patmenu

### ISSUE THREAD

**Issue by itstechpro** [WheezyE/Winelink#42]
Followed (KM4ACK) Jason's instructions to install John's new version of ARDOP, released the hold on the kernel and then did update and upgrade per Jason's post.  ARDOP works with no PTT problem.  Only difference between my intermediate version with kernel hold and this is that now VARA HF doesn't allow me to use the tune feature in soundcard setup ... error message states a link to RMSExpress is necessary to use the feature.

**Before executing the fix above, I had installed VARA per Jason's tutorial with a hold on the kernel to avoid the ARDOP PTT problem.  I noted that the install appeared to include RMS Express.  When I used VARA HF, the tune feature in sound card setup worked fine.  RMS express is apparently installed but the PTT fix may have broken the link ?????**

Other than the inability to use TUNE in VARA, everything seems to work normally.  I tested ARDOP and VARA with a winlink message to our County EC.
73,
Jules-K2KGJ

**Comment by WheezyE** [comment]
Thanks for the report.  I'll look into the connection issue between RMS Express and VARA.
I wonder if this might be related to [this Wine bug](https://bugs.winehq.org/show_bug.cgi?id=52521) with intermittent connection issues between RMS Express & VARA.

73,
Eric (KI7POL)

**Comment by WheezyE** [comment]
I think I'm going to close this issue for now as just a basically known bug in Wine and document it in the known bugs section.  I did some more digging though and think most users won't encounter this in new versions of RMS Express (1.7.1.0 or so and higher).
 - VARA HF's "Tune" button works on my Pi4B whenever RMS Express successfully connects to VARA HF's TCP port.
 - The "Tune" button only working when RMS Express is running is normal behavior on Windows.
 - Newer versions of RMS Express now restart VARA HF whenever TCP connection cannot be established, so users shouldn't probably be bothered by this much anymore (except for VARA HF P2P sessions, which don't seem to restart the modem until TCP connection)
