### ISSUE TITLE
Lack of installed 7zip seems to fail AutoHotkey installation

### ISSUE THREAD

**Issue by anttivs** [WheezyE/Winelink#43]
I used the script to install Winlink on Raspbian Buster. I did not have 7zip installed prior to first running the script, and the installation of AutoHotkey.exe failed on this line

```7z x AutoHotkey104805_Install.exe AutoHotkey.exe -y -bsp0 -bso0```

Subsequently VARA configuration failed.

The second try worked as the p7zip-full package had been installed by the script later.

**Comment by WheezyE** [comment]
This will be fixed in the future updates of the script. This patch-5 branch a ton of new updates since it is trying to incorporate multi-system wine install, so the new update might take a while.  I'll close this for now though
