### ISSUE TITLE
Manual entry for WineHQ key entry.

### ISSUE THREAD

**Issue by nomore1007** [WheezyE/Winelink#49]
Had to run "sudo wget -O /etc/apt/keyrings/winehq-archive.key https://dl.winehq.org/wine-builds/winehq.key" before running install script. I am using Mint 21 Cinnamon.

**Comment by WheezyE** [comment]
Thanks for the heads up. Is this with the latest commit on the patch-5 branch?  WineHQ has an error on their wiki page that tells users to install the GPG key into the wrong directory - I think I already fixed it though

**Comment by WheezyE** [comment]
For example: does running these commands work?
```
wget https://raw.githubusercontent.com/WheezyE/Winelink/WheezyE-patch-5/install_winelink.sh
bash install_winelink.sh
```
Thank you again for looking out

**Comment by nomore1007** [comment]
Yes this was with the latest patch-5 branch. I used that command, I had to figure it out :) I did see what I thought was the right command in your code, but I wasn't too sure how it worked to verify or edit it myself with any certainty.

Happy to help. This script worked great on my Pi4 64.

**Comment by WheezyE** [comment]
I think after merging #53, we can close this.  The key shouldn't have any more problems now that WineHQ is aware of their [.sources file issue](https://wiki.winehq.org/Ubuntu#Winehq_key_problems).
