### ISSUE TITLE
How do I bring back the Sound panel after install?

### ISSUE THREAD

**Issue by dnwk** [WheezyE/Winelink#5]

**Comment by WheezyE** [comment]
Do you mean VARA's settings menu?

**Comment by WheezyE** [comment]
VARA has a settings menu where you can set up sound card info, rms express also has its own settings menu too for setting up sound cards. Both of these programs run inside Wine, which has its own settings for audio which are located in `wine winecfg` . And I think everything runs through the Pi's pulseaudio or alsa drivers

**Comment by dnwk** [comment]
ah, winecfg is what I am looking for. Thanks

**Comment by dnwk** [comment]
I did successfully installed VARA FM.
