### ISSUE TITLE
Failure to load 

### ISSUE THREAD

**Issue by theranger53** [WheezyE/Winelink#57]
I am trying to install vara and winelink onto a raspberry pi 4b. I have actually tried on two different rpis with no success. I get to the same point each time. I am using the latest version of Buster 32 bit OS and am following the tutorial by KM4ACK Jason. I have a screenshot if I am able to place it in the dialogue.  It is not letting me put the screenshot in here. Imagine that. Any help would be appreciated.

**Comment by WheezyE** [comment]
fixed with updated ahk link, merged #59 into main branch
