### ISSUE TITLE
Autohotkey download and Winelink installation both fail

### ISSUE THREAD

**Issue by jasonburge** [WheezyE/Winelink#58]
Unsure why this is happening. I have a stable internet connection and the winelink.log file is unhelpful.
![Screen Shot 2022-12-22 at 12 58 25 PM](https://user-images.githubusercontent.com/121262592/209225728-11034f41-f0fe-40d8-9716-0b69298024a8.png)

**Comment by SpudGunMan** [comment]
two days ago the version used was purged from GitHub 2.0 was released. the script is currently critical stop.

**Comment by SpudGunMan** [comment]
patch suggestion, https://github.com/SpudGunMan/Winelink/tree/ahk-patch

**Comment by theranger53** [comment]
Do they have any idea when a fix will be implemented as I have the exact same problem loading to a RPI 4b.

**Comment by SpudGunMan** [comment]
provided a patch on the comment prior if your in a bind and need it fast just use the fork

**Comment by theranger53** [comment]
Not in a bind really but I am very much new to using GitHub unless through a youtube tutorial and am provided a direct link to the script I need. Not the smartest cookie in the box you might say. Trying to use a tutorial by Km4ack to install Vara onto a raspberry pi 4. Thanks for comment will keep trying

**Comment by SpudGunMan** [comment]
for the moment just use this fork https://github.com/SpudGunMan/Winelink

**Comment by SpudGunMan** [comment]
Yup that will work

Also 

'''

curl -O https://raw.githubusercontent.com/SpudGunMan/Winelink/patch-repo-keys/install_winelink.sh && bash install_winelink.sh 

'''

**Comment by WheezyE** [comment]
fixed with updated ahk link, merged #59 into main branch
