### ISSUE TITLE
High CPU load with VARA

### ISSUE THREAD

**Issue by 5rm** [WheezyE/Winelink#6]
To run VARA HF properly I have to run without waterfall and reduce the application calls to minimum (2)
I also did overclock the PI4B 2GB and now things seem quite acceptable.
![Screenshot 2021-07-11 11 54 53](https://user-images.githubusercontent.com/6057178/125190372-747e7f00-e245-11eb-88c7-7749ee3c9f0b.png)
Would it be possible to have a separate script for VARA only?  Then no .Net needed and maybe more simple and reliable?

73 Jouko OH5RM

**Comment by WheezyE** [comment]
Thanks for testing. I’ll see if I can add an option to the script to just install VARA. Not installing .NET for users who just want VARA and don’t want RMS Express would speed install up quite a bit too.

**Comment by WheezyE** [comment]
Hey so, I appreciate the help, but I was noticing your profile pic is a reichsmark and I just need to ask: Are you a nazi sympathizer?

**Comment by 5rm** [comment]
No, on the contrary. German currency before and after nazi time has no political meaning for me, just a pic including my call. But if it bothers you or somebody else, I just changed it.

**Comment by WheezyE** [comment]
Oh awesome, I’m glad to hear that. Thanks for letting me know.  My family
fled Germany and it was the first thing I thought of.  That’s a great idea
about VARA and I’m planning to implement that soon

73

**Comment by 5rm** [comment]
VARA FM runs with less load than HF, so full display is in use.
Wine may not support HID devices (?), so did not get RA-Board type PTT work in VARA modem.
Instead used this on Linux side:
https://www.cantab.net/users/john.wiseman/Documents/CM108_PTT.html
Now VARA FM works OK with my Wouxun HT on 2m and 4m

**Comment by WheezyE** [comment]
Nice work with the real-world testing. I’ll try to look into the HID thing soon and get that other vara_only option implemented (just having a busy week this week). I’ve been planning to put VARA FM in the script too, just haven’t gotten around to it yet

**Comment by WheezyE** [comment]
Just some updates regarding VARA FM and getting the script to turn off the waterfall. I got some good experimenting done today to figure out a method, but am just short of time to complete the method to turn off the waterfall for now.  I'll pick this up again soon and then push my testing branch onto the main branch when it's all working.  Thank you again for testing!

Testing branch is here if you want to follow progress: https://github.com/WheezyE/Winelink/blob/testing-install_winelink.sh/install_winelink.sh

**Comment by WheezyE** [comment]
Thank you again for testing.  I just pushed 617fa77f5e2095076a5d3298e55eef5adfcc9b36 to add a "vara_only" argument that you can pass to the script (`bash install_winelink.sh vara_only`) to skip the installation of RMS Express.  I'll document that argument in the readme shortly. 
 I also added some commands to make the script automatically turn off VARA HF's waterfall (and VARA FM's graphics) after first-run configuration of soundcards.

How did you reduce applications calls?  I'm curious about maybe adding that too.

Now that the script has been updated, I'll start looking into HID devices and box86/wine again.  I'll close this thread too and open a new HID-related one in a couple days too if that's ok.

**Comment by 5rm** [comment]
What is the best way to remove the original version? 
I would like to try Vara only hf + fm version.
As I use pilinbpq as host I dont need varim. Pilinbpq uses separate application calls for different functions , cms, bbs, chat etc. 
Do you have the newest vara hf 4.4.4. in the new script?

**Comment by WheezyE** [comment]
If you want to remove everything, then:
1. Delete the desktop icons and then 
2. Type `rm -rf ~/.wine` to get rid of your wineprefix (which is where all the software gets installed).

To re-run the installer with just the vara installation, copy-paste these commands into the terminal:
```
wget https://raw.githubusercontent.com/WheezyE/Winelink/main/install_winelink.sh && \
     bash install_winelink.sh vara_only
```

Just to stay standardized, I'm still just using the latest VARA HF 4.4.3 version that the official rosmodem site is willing to host.  When they update, then this script will automatically pick that latest version.
