### ISSUE TITLE
VARA 4.7.3 possibly no longer compatible with linux

### ISSUE THREAD

**Issue by pe1rrr** [WheezyE/Winelink#66]
I have been doing some testing with José after he changed major parts of VARA to run through in-memory code obfuscation and anti-piracy systems.

This has added overhead which causes VARA to fail consistently when running on RPI4, causing ALSA underruns when used in a configuration sharing the audio devices with other TNCs such as ARDOP and packet, so just a heads-up: do not to upgrade to 4.7.3 if using dsnoop/dmix or relying on VARA working under linux.

4.7.2 is the last version without these (annoying) measures added by José (EA5HVK).

**Comment by SpudGunMan** [comment]
sheesh, if greed ruins this I hope FCC gets this app off the air - the https://github.com/Rhizomatica/mercury is a possible better solution some day

**Comment by SpudGunMan** [comment]
I just tested on a new build and with a digirig I see a waterfall!!! so .. you sure its dead? I haven't tried fully yet but will test more here ASAP -- ARDOP has its own issues.

**Comment by pe1rrr** [comment]
> I just tested on a new build and with a digirig I see a waterfall!!! so .. you sure its dead? I haven't tried fully yet but will test more here ASAP -- ARDOP has its own issues. 


Yes, I didn't mention that it is the link negotiation that fails when it attempts to connect to any other VARA system. I have done extensive testing with José and him releasing this version knowing it causes issues for us is a smack in the face. 

I believe I have fixed the ARDOP issues, which is addressed on the ARDOP groups.io list.

This is a completely working setup: https://eindhoven.space/radio-experiments/packet-radio/vara-ardop/raspberry-pi4-trifecta-tnc-bank-image-companion-documentation/

**Comment by SpudGunMan** [comment]
Better to share the fix vs the binary but cool project.

**Comment by pe1rrr** [comment]
> Better to share the fix vs the binary but cool project. 

Share binary? What do you mean?

**Comment by pe1rrr** [comment]
> Better to share the fix vs the binary but cool project. 

The fix is not in the binary (this statement confused me), it is a series of operating system adjustments that provide the solution. That document is literally it.

**Comment by SpudGunMan** [comment]
I am confused ardop isnt part of this project and you said VARA is broken but you fixed it but not to update. links to projects without answers, it sounds like your suggesting this project is dead and you have a solution but its for ARDOP?

**Comment by pe1rrr** [comment]
> I am confused ardop isnt part of this project and you said VARA is broken but you fixed it but not to update. links to projects without answers, it sounds like your suggesting this project is dead and you have a solution but its for ARDOP?

Urgh. Ok, crossed wires here-

I mentioned ARDOP because in my particular scenario, the audio interface is using a dsnoop/dmix setup in order to share the interface with VARA, Packet and of course ARDOP _at the same time_. This induces some small latency but has been working perfectly find up until version 4.7.3 of VARA which has added realtime memory encryption/obfuscation which taxes the RPI4 too much in my setup-

I am not sure if VARA connection establishment is broken when accessing the audio interface directly/priority as this is something you will need to test for in Winelink.

The thing to look out for in VARA is stuttering audio in the 88bps and higher mode after the MFSK handshake has finished.

I forgot I had mentioned ARDOP in thr subsequent posts and saw your remark about 'ARDOP has its own issues' as an opportunity to respond that there is a workaround for ARDOP's known issue with newer Linux kernels (I assumed you referred to this because there aren't many other issues I am aware of).


Hope this helps.

🫥

**Comment by SpudGunMan** [comment]
got ya. I was able to connect with FM .. so it sounds like your testing reflects a dead project. this is sad news for sure. 

have you mentioned this to the groups.io vara, I am very upset to hear this is dead because of shareware greed

**Comment by SpudGunMan** [comment]
I shot a dart out on groups for vara

**Comment by SpudGunMan** [comment]
I also shot a note to varac team

**Comment by WheezyE** [comment]
> I have been doing some testing with José after he changed major parts of VARA to run through in-memory code obfuscation and anti-piracy systems.
> 
> This has added overhead which causes VARA to fail consistently when running on RPI4, causing ALSA underruns when used in a configuration sharing the audio devices with other TNCs such as ARDOP and packet, so just a heads-up: do not to upgrade to 4.7.3 if using dsnoop/dmix or relying on VARA working under linux.
> 
> 4.7.2 is the last version without these (annoying) measures added by José (EA5HVK).

That is bad news. I’ll have to test the new version and see if things are totally unusable.  On one hand, I’m not surprised - VARA was never intended for Linux in the first place and has a steep price tag for what it provides. On the other hand, maybe this will help wake up the Winlink community to not want to rely so much on pay-for services. I hope one day a newer generation will bring the hobby back to its open-source community roots.

Maybe this will inspire someone to write an open-source mode similar to VARA and push the field forward.

Thank you for the heads up!

**Comment by SpudGunMan** [comment]
88k limit is still acceptable for winlink emcomm 

What I did experience is some possible glitching and lock ups. Around the inspection time for license. Not always but 

I personally am very frustrated as I was working on some high speed experimental stuff. This stinks.

But 88k isn't horrible for sailmail(winlink). If stability can be corrected but on top of varac stability ooof. All for obfuscation and prevention of theft from dishonest? Lamenting sigh of pain. 

Project mercury uses similar coding. 

Yes thanks for raising the alarm

**Comment by WheezyE** [comment]
> sheesh, if greed ruins this I hope FCC gets this app off the air - the https://github.com/Rhizomatica/mercury is a possible better solution some day



> sheesh, if greed ruins this I hope FCC gets this app off the air - the https://github.com/Rhizomatica/mercury is a possible better solution some day

PACTOR is pay-for and has been on the air for a long time, but I appreciate the sentiment. I wish this communication hobby was more financially accessible so more people could communicate.

That Mercury project looks nice. I wish them the best.

**Comment by SpudGunMan** [comment]
Heard back the offending code may have been removed.

**Comment by WheezyE** [comment]
Interesting.  The current version is still 4.7.3.  When the new version comes out, @pe1rrr would you be able to check to see if you're finding the same slow-downs on RPi4?

In the meantime, we might all want to download these old VARA's while they're still online and hold onto the files:
[VARA HF v4.7.2 (High Performance HF Modem)](https://mega.nz/file/SOBXTaTb#8mOBDOzSzVvVipmu6LJlyX4HSPuE-upwq5dtWw3WIHg)
[VARA FM v4.2.8 (VARA for FM transceivers)](https://mega.nz/file/3DhHTBJI#YxL77lHoJzgp6QpKcDxrIikrtQkKa91vEXbqjyYDni4) 
[VARA SAT v4.3.6 (VARA for QO-100 geostationary SAT)](https://mega.nz/file/7fohUbLD#Cy1R11R2JAkaP1t3HWwWtdNtlwKo9x-9SyhKFycy-CQ)
[VARA Chat v1.3.4 (Easy Text and File transfer chat)](https://mega.nz/file/fLR3GTJR#ySLEZOqohpuz3CQraO1pPhqrKeWrnk7Q_XOEMCJZYKc)
[VARA Terminal v1.2.0 (VARA dumb terminal for BBS’s)](https://mega.nz/file/uexDQYrK#KJKPHJinhuG_B4sCzRcvfTVLE7S9H7P9MsAbegd46hI)
_Official links found on [internet archive](https://web.archive.org/web/20230128005409/https://rosmodem.wordpress.com/) - internet archive doesn't archive mega links though so download while you can_

**Comment by SpudGunMan** [comment]
Yea it was, i am going to flash a pi today, license and test for lockup. 

I was testing on free yesterday which didn't help matters much either.

**Comment by WheezyE** [comment]
> Heard back the offending code may have been removed.

Oh great! I see your post [on the vara groups.io](https://groups.io/g/VARA-MODEM/message/5358). Just posting here to have everything in one place:

>I did hear back from Jose on the matter and it seems a positive direction for the concerns and I do hope the mixed bag of user group continues to do wacky things with ham radio. We are all learning and thanks for tolerating. Sorry for the disruption. The response was.. 
>
>>That changes were discarded.

**Comment by WheezyE** [comment]
Also just for clarity: I was able to finally test-run VARA 4.7.3 today on my Pi4 (I'm still too lazy to get my general, so can't test OTA connections yet).

Running VARA 4.7.3 on RPi4 (through box86/wine), I can open the program, input my VARA license code, and still run the program without lockups.  Like pe1rrr has already mentioned, I guess this new security code CPU overhead would create lockups when the system was being taxed, like while making connections / transferring data / talking to other TNC's running on the Pi4 at the same time.

**Comment by SpudGunMan** [comment]
something you and the XYL can get in a weekend! Technician and upgrade general!! New ham! 

Yes I suspect the BPQ use case (dual modems) is solved with the solutions provided and pe1rrr laid out. 

(I would also be interested if wine/ardop.exe in this project would remedy some issues with ALSA?)

**Comment by pe1rrr** [comment]
This is a recording of the problem so you can recognise it:

https://youtu.be/xmjZ2t5fxE0

Please ignore the fact this screen shows 5 x RPI4 systems, the one RPI4 being recorded is a console server, the other 4 systems- one is EI2GYB in Ireland and the other three are my 10m/20m/40m systems. 

The problem occurred only in VARA 4.7.3 (tainted) *even with no other TNCs running* the other TNCs running did not tax it because VARA runs on a single core as do the others on their own core in the example shown.

**Comment by pe1rrr** [comment]
@WheezyE @SpudGunMan I've updated the previous comment with additional info.

**Comment by SpudGunMan** [comment]
![perfmon](https://user-images.githubusercontent.com/12676665/221037757-457b35d5-5297-4477-ae52-4bbcc26fb5e2.jpg)
here is just opening the applications no use of app

**Comment by SpudGunMan** [comment]
> The thing is, the 4.7.2 original installs worked sufficiently well with occasional problems that went away after VARA had been left running a little while (not stuttering audio, but failure to link on a first attempt after start up).
> 
> On the other hand, 4.7.3 issues cropped up and broke immediately off the bat, so to speak.

I share these observations. 4.7.3 is not ideal, I did respond to the email from Jose commenting this is not working as he suggested it should be.

**Comment by WheezyE** [comment]
Thank you @pe1rrr for the videos and explanations!

**Comment by pe1rrr** [comment]
Hi @WheezyE @SpudGunMan 

I have done extensive new tests fo VARA 4.7.4 and am happy to report that the functionality is fully restored to the same performance with 4.7.2. The ChangeLog doesn't mention anything but I presume this release has been gutted of the troublesome code.

Phew!

Here is a twitch stream I will archive later on YouTube of the entire process including installing on  multiple systems and doing long distance RF as well as local (fancy pants BBS forwarding).

https://www.twitch.tv/videos/1752369892

**Comment by oh2lak** [comment]
Exactly what has FCC to do with VARA-modem?

..
Erik OH2LAK TF3EY

**Comment by SpudGunMan** [comment]
There is a rule in laws in usa which have archaic language terms which complicate matters. 

Bits baud bandwidth. Three B's needing clarification. Currently under submission for review. 

All of which is out of scope for much banter on git but happy to pontificate pointlessly elsewhere!

de k7mhi via Qrz

**Comment by WheezyE** [comment]
> Exactly what has FCC to do with VARA-modem? .. Erik OH2LAK TF3EY
> […](#)

That’s a good question since some people on forums have been frustratedly saying the FCC should ban VARA. As far as I know, the FCC has no control at all over VARA as software. They wouldn’t need to regulate any part of it, especially not any anti piracy features. If VARA was programmed to work on a frequency or at a speed that was not allowed in the USA, I believe that would be the radio operator’s fault for using the modem in a way that didn’t comply with FCC.

**Comment by kyhwana** [comment]
> > Exactly what has FCC to do with VARA-modem? .. Erik OH2LAK TF3EY
> > […](#)
> 
> That’s a good question since some people on forums have been frustratedly saying the FCC should ban VARA. As far as I know, the FCC has no control at all over VARA as software. They wouldn’t need to regulate any part of it, especially not any anti piracy features. If VARA was programmed to work on a frequency or at a speed that was not allowed in the USA, I believe that would be the radio operator’s fault for using the modem in a way that didn’t comply with FCC.

VARA is a proprietary undocumented closed source mode, as such it's "obfuscation" and doesn't belong on the ham bands.

**Comment by oh2lak** [comment]
So then PACTOR is OK to use on ham bands, being even more proprietary and
$$$?

VARA is a rather nice modem and fits very well to ham bands. It is solely
its developers decision to keep it closed-source. He is not making a lot of
money with it with the one-time registration fee which includes free
updates. It is a rather modest cost to support the developer in my opinion.
How Jose has done the programming with inclusions of anti-piracy code and
some sort of obfuscation is his choice and right to protect his copyright
to the code. It is not doing any obfuscation on the air interface.

What comes to FCC and the bitrate/symbol/speed limits, every ham in the US
should talk with their representatives that those limits should be lifted,
they are not part of modern communication regulation anymore. Technology
has made a huge leap in the last 20 years and limiting the data modes to
sub-telephone line modem-era is no way reasonable or needed anymore.

What I have missed in this thread about VARA-HF not being compatible
anymore with Wine or other windows emulators is that nobody seemed to
contact Jose directly to present the issue to him? Few rumours through
third parties yes but this project is already rather big so why not talk
directly with the 'vendors' as well? Irad who makes VarAC has done a
magnificent job by adding 'Linux compatibility' to the settings of VarAC.

73,
Erik OH2LAK TF3EY









..
Erik OH2LAK TF3EY

**Comment by kyhwana** [comment]
> So then PACTOR is OK to use on ham bands, being even more proprietary and $$$?
No, PACTOR isn't OK either.

"Anti-piracy" code for a close sourced, undocumented protocol is an anathema to what ham radio is, or should be about.

The FCC 300 baud limit is strictly a US ham concern, and not concern of mine as a ZL ham.

If you read earlier comments you'll see that it's implied that someone already emailed him. Of course this wouldn't have been necessary if the vara modem was open source. "Anti-piracy" features wouldn't be breaking non-windows support of a modem used on the ham bands.

**Comment by pe1rrr** [comment]
> What I have missed in this thread about VARA-HF not being compatible
> anymore with Wine or other windows emulators is that nobody seemed to
> contact Jose directly to present the issue to him? Few rumours through
> third parties yes but this project is already rather big so why not talk
> directly with the 'vendors' as well? Irad who makes VarAC has done a
> magnificent job by adding 'Linux compatibility' to the settings of VarAC.
> 
> 73,
> Erik OH2LAK TF3EY
> 
> 

Read the very first line in this issue post. I worked directly with José on this.

**Comment by oh2lak** [comment]
Sorry, I missed that. I only saw people posting to other VARA-groups and
such to get attention to this issue.

Great work and thanks for the time & knowledge put into this project!

73,
Erik OH2LAK TF3EY
