### ISSUE TITLE
Consider adding PiLinBPQ?

### ISSUE THREAD

**Issue by WheezyE** [WheezyE/Winelink#7]
https://www.cantab.net/users/john.wiseman/Documents/PINodeSetup.html
https://www.cantab.net/users/john.wiseman/Documents/Downloads.html
https://github.com/pe1rrr/linbpq_rtg

**Comment by 5rm** [comment]
I use pilinbpq + your winelink created vara, good combination.
But as pilinbpq is a real linux program, it is easy to install with wget etc, but could of coarce be included in script too. Then maybe some very simple bpq32.cfg with vara and telnet ports only.
To use pilinbpq with vara and piqtsoundmodem the same time on a soundcard needs pulse audio. I have not yet managed to get vara work with pulse audio. I tried winetricks but the usb audio codec is not appearing in vara soundcard settings.
The other thing which could be included in winelink script is vara chat, which is the easiest way to use vara modem

**Comment by WheezyE** [comment]
Thank you for the continued help and support.  I've been looking into vara chat, which sounds really great.  It's currently not working with box86, but I'm hoping that fixing RMS Express will get vara chat working too.  Not sure the timeframe on this, but I'm adding it as a top priority for this project.

I'll look into PiLinBPQ cfg's too probably a bit down the road.  If you had a cfg file you wanted to include too at any point, I'd be happy to merge it into this repository, though no pressure.  I think that's a great idea.

Pulse Audio have problems with the ALSA setup in wine (in the script) that VARA needs.  I'll try to look into this down the road too.

**Comment by 5rm** [comment]
This is a simple bpq32.cfg file with Telnet and VARA ports. Chage MYCALL and LOCATOR according your situation.
Uncomment LINMAIL and APPLICATION BBS if you want them too in addition to WL GW. This configuration assumes VOX (Signalink), for PTT but you may add "Rigcontrol" to the VARA Port if rig supports CAT or if your sound carrd is CM108 type

; Basic RMS configuration

SIMPLE ; This set a whole load of paramters to reasonable defaults

LOCATOR=XXnnXX ; Set to your Grid Square to send reports to the BPQ32 Node Map system
NODECALL=MYCALL

INFOMSG:
MYCALL's RMS Gateway
***

PORT
 PORTNUM=1
 ID=Telnet Server
 DRIVER=TELNET
 CONFIG
 LOGGING=1
 CMS=1 ; Enable CMS Gateway
 CMSCALL=MYCALL ; CMS Gateway Call for Secure CMS Access(normally same as NODECALL)
 CMSPASS=PASSWORD ; Secure CMS Password
 HTTPPORT=8080 ; Port used for Web Management
 TCPPORT=8010 ; Port for Telnet Access
 FBBPORT=8011 ; Not required, but allows monitoring using BPQTermTCP
 MAXSESSIONS=10
 CloseOnDisconnect=1 ; Close Telent Session when Node disconnects
 USER=user,password,MYCALL,"",SYSOP
ENDPORT
 
 ; Add Radio Port(s) Here
PORT
 PORTNUM=2
 ID=VARA
 DRIVER=VARA
 CONFIG
 ADDR 127.0.0.1 8300 
ENDPORT
 
 APPLICATION 1,RMS,C 1 CMS,MYCALL-10
; APPLICATION 3,BBS,,MYCALL-2
;LINMAIL

**Comment by 5rm** [comment]
Something has changed, the VARA only option is no more working, installs WinlinkExperss and the loop never ends

**Comment by WheezyE** [comment]
Thanks for the config file and for the report.  I'm checking the script now and will merge the config after I test it (after I figure out how linbpq works lol)

**Comment by WheezyE** [comment]
![2623E389-5345-43CB-91E6-7317B0C9280D](https://user-images.githubusercontent.com/29649598/129452260-ee5f8022-11b4-412d-861b-3459c2adbdc8.png)
![B68F1FBD-BAFF-45A9-BE64-86D700C41ED2](https://user-images.githubusercontent.com/29649598/129452262-8af7bda5-2dac-4c42-a362-28e4cbcbac74.png)
I’m not getting any problems with the `vara_only` option on my end with RMS Express or loops, but I didn’t find that the new VARA 4.4.5 is causing the AHK soundcard setup script to freeze.
Maybe try reinstalling?

**Comment by 5rm** [comment]
Very strange... The first version of vara_only abt two weeks ago did run well and did not install WinlinkExpress, now it seems like the vara_only has no effect it installs the .Net etc.
Are you sure we are using the same script? I use the one from github, nothing in my own PC.
I have rerun it many times and always ends to some loop without clean end.

**Comment by WheezyE** [comment]
Hm strange indeed. I deleted my wineprefix, deleted all scripts, and then ran these commands for a fresh install, script downloaded from the GitHub:
```
wget https://raw.githubusercontent.com/WheezyE/Winelink/main/install_winelink.sh
bash install_winelink.sh vara_only
```
I’ll try reflashing my Pi and trying again

**Comment by 5rm** [comment]
![Screenshot 2021-08-15 10 25 07](https://user-images.githubusercontent.com/6057178/129472991-53581acc-43c9-4607-9fc9-0842ca1f0eed.png)
![Screenshot 2021-08-15 10 35 56](https://user-images.githubusercontent.com/6057178/129473005-dfa4105c-b276-4087-8d0d-e03b6719dec1.png)

**Comment by 5rm** [comment]
Using blanc SD I tried vara_only using ssh as my PI has no display or keyboard. It stopped asking to go to winecfg audio tab, but the winecfg does not appear.
Next I moved using VNC and X-terminal on pi itself.  That worked OK and I got VARA HF, VARA FM and vARIM installed OK. So there is something strange when using remote ssh for installing.

There seems to be a problem in bpq32.cfg when I pasted it.  the stars are converted to line at INFOMSG:
correctly it should be:
INFOMSG:
MYCALL's RMS Gateway
***
no line after that. (in Edit mode the stars show OK)

**Comment by 5rm** [comment]
The same happening again,  I dont know how to enter star chrs "***"

**Comment by 5rm** [comment]
![Screenshot 2021-08-15 14 24 16](https://user-images.githubusercontent.com/6057178/129476874-f35851b4-4aaa-44d5-84ca-f90f83e0b9e1.png)

**Comment by 5rm** [comment]
Now running OK, but VARA HF CPU load at over 80%

**Comment by 5rm** [comment]
![Screenshot 2021-08-15 14 29 02](https://user-images.githubusercontent.com/6057178/129477003-53ea0297-95b0-4b18-b9b8-ad9d809b48b7.png)

**Comment by 5rm** [comment]
![Screenshot 2021-08-15 14 32 49](https://user-images.githubusercontent.com/6057178/129477118-70f71321-65df-4e2c-8799-941eec7e8064.png)

**Comment by 5rm** [comment]
![bpq32 cfg](https://user-images.githubusercontent.com/6057178/129480466-b3594aba-4f87-45dd-905d-5ef969847757.jpg)

**Comment by 5rm** [comment]
https://www.dropbox.com/s/yewqy4gzxwt8ch5/bpq32.cfg.jpg?dl=0

this is how the bpq32.cfg looks at my setup

**Comment by WheezyE** [comment]
> Next I moved using VNC and X-terminal on pi itself. That worked OK and I got VARA HF, VARA FM and vARIM installed OK. So there is something strange when using remote ssh for installing.

Ah yes that makes sense now. The way I’ve got the script set up right now, Wine needs a graphical environment to run its GUI’s. I be that when you were using SSH, Wine would not have found an X11 (graphics environment) to send GUI output to and would not pop up winecfg. I’ve been using VNC to run my pi this whole time but I’ll try adding detection for ssh so that the script doesn’t crash if run with SSH

**Comment by WheezyE** [comment]
> There seems to be a problem in bpq32.cfg when I pasted it.  the stars are converted to line at INFOMSG:
correctly it should be:
> INFOMSG:
> MYCALL's RMS Gateway
> ***
> no line after that. (in Edit mode the stars show OK)

That’s ok, don’t worry I can see your text in edit mode and I’ll copy that into the repo soon. Thank you again for the cfg file. The problem is just that GitHub has its own markup language, so it thinks your stars are you trying to make a line in the comments. If you want GitHub to not interpret your text (if you want GitHub to display your text literally), you can use three ` marks in a row above and below your text to display code like this:
```
Code here
*****************
Use three of these ` to end the codeblock
```

**Comment by 5rm** [comment]
Could there be a version for normal linux without Box86 and for VARA only, no .dosnet?

**Comment by 5rm** [comment]
The above to use Vara with linbpq on Mint (debian) PC

**Comment by WheezyE** [comment]
Oh yes, for that you would just need to install wine and winetricks (with apt), then upgrade winetricks, configure the wineprefix with winetricks, then install VARA.

That might look something like this:
```bash
sudo apt install wine winetricks --install-recommends -y
sudo winetricks --self-update
wine wineboot 
wine winecfg
winetricks -q vb6run pdh_nt4 win7 sound=alsa # for VARA

sudo apt-get install curl megatools p7zip-full -y
    
    mkdir downloads; cd downloads
        # Download / extract / install VARA HF
        VARAHFLINK=$(curl -s https://rosmodem.wordpress.com/ | grep -oP '(?=https://mega.nz).*?(?=" target="_blank" rel="noopener noreferrer">VARA HF v)') # Find the mega.nz link from the rosmodem website no matter its version, then store it as a variable
        megadl ${VARAHFLINK}
        7z x VARA\ HF*.zip -o"VARAHFInstaller"
        wine VARAHFInstaller/VARA\ setup*.exe
    cd ..
```

A future version of this script that detects linux version and auto installs components is planned - it’s just been a busy season. But that is a goal

**Comment by 5rm** [comment]
![Screenshot 2021-08-31 16 32 34](https://user-images.githubusercontent.com/6057178/131511958-7e23a62d-c181-4fa0-b082-229939d1eb70.png)

**Comment by 5rm** [comment]
If I start VARA from bpq32.cfg line:
ADDR 127.0.0.1 8300 PTT CAT PATH wine /home/pi/.wine/drive_c/VARA/VARA.exe
Whit is the normal way to start a modem, I get The above BOX saying there are two VARAs from same folder.  Do you know the right format for PATH?

**Comment by 5rm** [comment]
The above happens if you try to start VARA from linbpq PATH. As it is quite slow to start VARA under wine, it tries to start again. G8BPQ is informed abt this issue,

**Comment by oh6ij** [comment]
Hi Eric! 
I tried your install script for VARA -> "...something like this..."  above with my Linux Mint. 
All OK but the cURL-part did not work, did it manually. VARA installed OK and is working with LinBPQ.
Now I would like to install WinLink Express also. I have taken some info from K6ETA for this and added to your script. Can You please look at it and tell me if something is missing or is too much?
I'm new in Github and new in Linux. Please be gentle with me... 
Ykä OH6IJ

paste here below:

# K6ETAadd for permissions: 
sudo usermod -a -G dialout $USERNAME
sudo usermod -a -G tty $USERNAME
sudo usermod -a -G audio $USERNAME

# if total remove of wine is needed delete # on the next lines
mv ~/.wine ~/.wineBU
rm -rf ~/.wine
rm -rf ~/.cache/winetricks

sudo dpkg --add-architecture i386 #K6ETA add

export WINEARCH=win32 #K6ETA add

sudo apt install wine winetricks --install-recommends -y

# sudo apt-get install wine-stable??? #K6ETA add

sudo apt-get install gnome-exe-thumbnailer #K6ETA add

ln -s /dev/ttyUSB0 ~/.wine/dosdevices/com1 #K6ETA add

gedit ~/.wine/system.reg # K6ETA add for some edits 

sudo winetricks --self-update

wine wineboot 

wine winecfg

winetricks -q dotnet35sp1 #K6ETA add the whole MS dotnet takes time
winetricks vcrun2015 #K6ETA add

winetricks -q vb6run pdh_nt4 win7 sound=alsa # for VARA

sudo apt-get install curl megatools p7zip-full -y

mkdir downloads; cd downloads

# Download / extract / install VARA HF
# Find the mega.nz link from the rosmodem website no matter its version, then store it as a variable
# did not work, did manually

VARAHFLINK=$(curl -s https://rosmodem.wordpress.com/ | grep -oP '(?=https://mega.nz).*?(?=" target="_blank" rel="noopener noreferrer">VARA HF v)') 

megadl ${VARAHFLINK}

7z x VARA\ HF*.zip -o"VARAHFInstaller"

wine VARAHFInstaller/VARA\ setup*.exe

cd ..

ls -l ~/.wine/dosdevices/ # to see the COM-port number

**Comment by WheezyE** [comment]
> The above happens if you try to start VARA from linbpq PATH. As it is quite slow to start VARA under wine, it tries to start again. G8BPQ is informed abt this issue,

Thank you. I still hadn’t had a chance to try LinBPQ and was wondering what could be causing two launches of VARA. That makes sense. If VARA is already running before opening LinBPQ, does LinBPQ still not detect VARA?

**Comment by WheezyE** [comment]
@oh6ij It’s always great to have more people interested in RMS and Linux. Hm I’ll have to try those steps on a Linux Mint VMware container on my laptop next chance I get. Those steps look ok at first glance. I didn’t realize there was so much interest in other Linux platforms other than Pi. I’ll have to look into implementing those soon.
73 KI7POL

**Comment by 5rm** [comment]
Yes Eric, if you start VARA from desktop icon before linbpq, then no problem. But as said G8BPQ is working on this issue and then also start from linbpq possible.

**Comment by oh6ij** [comment]
Eric,
I tried your cURL above  separately and it creates the following link:
https://mega.nz/file/6C4AlBYR#yEX5Ee_4It85ODxMfRCPwzBonzxPcj18afb9qjm2S8c

That is correct but...

 "megadl" says "invalid" when trying that link:

WARNING: Skipping invalid Mega download link: https://mega.nz/file/6C4AlBYR#yEX5Ee_4It85ODxMfRCPwzBonzxPcj18afb9qjm2S8c

The page which opens with Chrome from that link has a "Download"-button and you have to press that to get the file.
Ykä

**Comment by WheezyE** [comment]
@oh6ij Don’t forget to run this command `sudo apt-get install curl megatools p7zip-full -y` before running curl or megadl

**Comment by WheezyE** [comment]
@oh6ij This turned out to be an issue with using the older 1.10.2 version of megadl in the Linux Mint repo.  The newer version of megadl parses new mega links correctly, but the older version parses links the way they used to be formatted. I'll look at a workaround. Thank you for reporting this bug

**Comment by WheezyE** [comment]
@oh6ij Try this rough draft script I whipped up today for Linux Mint (on x64 Linux PC's - Not raspberry Pi)
```
wget https://raw.githubusercontent.com/WheezyE/Winelink/main/docs/experiments/x86-64_Linux_distros/Debian-Ubuntu_x64.sh && bash Debian-Ubuntu_x64.sh
```
That should fix the VARA downloading problem and hopefully get most things installed ok.  I haven't really tested it much, but I'll try to get it more stable and then integrate it into the main script.

**Comment by 5rm** [comment]
![image](https://user-images.githubusercontent.com/6057178/131798509-7c33316e-60cc-4fe5-8f4a-4260e61a4ce5.png)

**Comment by 5rm** [comment]
There is a new linbpq/pilinbpq version 6.0.22.3 which fixes the double starting of VARA.
A new parameter AutoStartDelay=15000 to put into config part of VARA PORT. The number is millisec

**Comment by oh6ij** [comment]
Wow! I ran your "whipped up" script and all ok, I think. So much lines in your script....
I started WLE with VARA  on my Mint and made a contact with my GW-station. 64kilos in 3.7 minutes.
All seems to be OK.
I'll test more (VARA with linbpq) when I return from southern Finland on Sunday.
Thanks Eric! 73's
Ykä OH6IJ

**Comment by oh6ij** [comment]
This morning I tested some more. Got good speeds between my two stations, abt. 20000 bytes per minute, max speedlevel over 8000bps. So no problem there. Some notes:
1. Many times I cannot close the Winlink windows. I have to kill them and start over.
2. The VARA log does not appear from the VARA menu. I have to go to wine's c_drive
3.  Scanning with Linbpq is OK, radio freq changes. No more tests yet.
Ykä OH6IJ

**Comment by 5rm** [comment]
![54152B15-A941-42F1-9505-FDCCE993D126](https://user-images.githubusercontent.com/6057178/132201171-fb89f04f-af77-4208-a9d4-048eb487abc9.png)

**Comment by 5rm** [comment]
Vara + pilinbpq running fine on PI4, just had the above connect with OH6IJ on 60m

**Comment by WheezyE** [comment]
That’s amazing. Thank you for the testing! I’ll probably try to get pilinbpq added pretty soon to the script too

**Comment by 5rm** [comment]
Well pilinbpq is network/gw/bbs software.  It can do abt the same and more than windows Winlink Trimode server+RMS Relay. But as said it can easily be installed with wget… . So best close this issue. 
More important is a robust install script for VARA . 
73 Jouko oh5rm

**Comment by WheezyE** [comment]
Thank you for sharing your knowledge and experience with PiLinBPQ. I will definitely keep this in mind for future iterations of the script or for future install instructions

I’ll close this for now, but might re-open it in the future.
73 de KI7POL
