### ISSUE TITLE
errors in 'Creating a new wineprefix.'

### ISSUE THREAD

**Issue by SpudGunMan** [WheezyE/Winelink#70]
I have been seeing some panic's at this stage

```
wine: created the configuration directory '/home/pi/.wine'
wine: Call from 7B0110D6 to unimplemented function mfplat.dll.MFTRegister, aborting
wine: Unimplemented function mfplat.dll.MFTRegister called at address 7B0110D6 (thread 0088), starting debugger...
wine: configuration in L"/home/pi/.wine" has been updated.
```

```
reating a new wineprefix.  This may take a moment . . .

wine: created the configuration directory '/home/pi/.wine'
wine: Unhandled page fault on execute access to 00000000 at address 00000000 (thread 0088), starting debugger...
wine: configuration in L"/home/pi/.wine" has been updated.
```

pi4 4gb 32 and 64 distro using rasp pi imager

another interesting error possibly releated, `winecfg` also is not loading hang at `Executing wine winecfg -v win7`

error seen passing by..

```
Call from 7B0110D6 to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
```

full lockup at 
```
/home/pi/wine/bin/wine C:\windows\system32\rundll32.exe setupapi,InstallHinfSection DefaultInstall 128 \\?\Z:\home\pi\wine\share\wine\wine.inf
```

I am a little concerned that the resources of a 4GB Pi and box emulation may also be a factor as free memory is under 200mb typically I notice

I have moved my 2024 work to intel processors for now

**Comment by WheezyE** [comment]
It took me a while to realize that I think this is from box86's dynarec having problems with newer Debian packages.  I think I've worked around some of this with commit bfdf35ed43291587ad86a2e4a986ddbe21b35d47 but I support the move to a i386 OS for more reliability.  There will still probably be errors in the terminal but hopefully it shouldn't freeze now.  I'll close this issue, but feel free to re-open.
