### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by EveliinaL** [WheezyE/Winelink#71]
Hi!
I want to install on my linux (Debian) but it doesn't install because of missing files it says. 
I have VarAC downloaded on my linux, but can't download winelink
How can I do?

**Comment by WheezyE** [comment]
Hello, sorry for just getting to this. If the script says that there are files missing, try re-installing at a later time. If the downloads still don’t work, try downloading from a different internet connection or check your router’s firewall (my work blocks Debian repo downloads for example but my home doesn’t).
