### ISSUE TITLE
Install winelink fails

### ISSUE THREAD

**Issue by FredB1959** [WheezyE/Winelink#77]
During install of vara on a raspberry pi 4 I get an download error while my internet connection is working. With every retry it happens at the same point of the install.

See below the dotted line the error report.

------------------------------------------------------------------------------------------------------------------------
Setting up your wineprefix for VARA . . .

Using winetricks 20230212-next - sha256sum: fe0550e0d843214f87dcb0f4aa591be0046fa93db7b8330217dd926258e628fc with wine-7.1 and WINEARCH=win32
Executing w_do_call vb6run
Executing load_vb6run 
Executing cd /home/pa8f/.cache/winetricks/vb6run
Downloading https://web.archive.org/web/20070204154430/https://download.microsoft.com/download/5/a/d/5ad868a0-8ecd-4bb0-a882-fe53eb7ef348/VB6.0-KB290887-X86.exe to /home/pa8f/.cache/winetricks/vb6run
--2023-10-06 14:32:15--  https://web.archive.org/web/20070204154430/https://download.microsoft.com/download/5/a/d/5ad868a0-8ecd-4bb0-a882-fe53eb7ef348/VB6.0-KB290887-X86.exe
Resolving web.archive.org (web.archive.org)... 207.241.237.3
Connecting to web.archive.org (web.archive.org)|207.241.237.3|:443... connected.
Unable to establish SSL connection.
Executing cd /home/pa8f/.cache/winetricks/vb6run
Downloading https://web.archive.org/web/2000/https://web.archive.org/web/20070204154430/https://download.microsoft.com/download/5/a/d/5ad868a0-8ecd-4bb0-a882-fe53eb7ef348/VB6.0-KB290887-X86.exe to /home/pa8f/.cache/winetricks/vb6run
--2023-10-06 14:32:31--  https://web.archive.org/web/2000/https://web.archive.org/web/20070204154430/https://download.microsoft.com/download/5/a/d/5ad868a0-8ecd-4bb0-a882-fe53eb7ef348/VB6.0-KB290887-X86.exe
Resolving web.archive.org (web.archive.org)... 207.241.237.3
Connecting to web.archive.org (web.archive.org)|207.241.237.3|:443... connected.
Unable to establish SSL connection.
------------------------------------------------------
warning: Downloading https://web.archive.org/web/2000/https://web.archive.org/web/20070204154430/https://download.microsoft.com/download/5/a/d/5ad868a0-8ecd-4bb0-a882-fe53eb7ef348/VB6.0-KB290887-X86.exe failed
------------------------------------------------------
Winetricks failed to download/install VB6 or PDH.DLL!
Box86 with Dynarec v0.2.7 14113faa built on Oct 10 2022 20:20:17

Winelink installation failed.

If a download failed, please check your internet connection and try re-running 
the script.
For help, please reference the '/home/pa8f/winelink\winelink.log' file
You can also open an issue on github.com/WheezyE/Winelink/

**Comment by schinds** [comment]
I've experienced this problem, but it's intermittent. If I wait a few minutes and run the script again the dll's are downloaded. Perhaps the source server gets overloaded.

**Comment by WheezyE** [comment]
I believe this is from Internet Archive being unreliable sometimes.  I'll close this for now. Feel free to re-open if this comes up again.
