### ISSUE TITLE
download for VARA changed 

### ISSUE THREAD

**Issue by SpudGunMan** [WheezyE/Winelink#84]
the MEGA downloads are failing as it appears all binary moved to here
https://downloads.winlink.org/VARA%20Products/

you can get all the winlink and vara binary locally with 
`wget -r -A "*.zip" 'https://downloads.winlink.org/VARA%20Products/'`

**Comment by schinds** [comment]
As a workaround, I was able to download the VARA setup files via the link above and install them manually.

**Comment by WheezyE** [comment]
@nomore1007 had a working PR though I did not see it until now. I've updated the download links.
